### ISSUE TITLE
Fix the build configuration so that `make` doesn't need to be repeated

### ISSUE THREAD

**Issue by pirapira** [pirapira/bamboo#268]
Currently, some build dependency seems missing around the parser and the lexer.  As a result, a single `make` does not finish the compilation.  In the Travis configuration, `make; make; make; make; make; make; make; make` compiles the codebase.  This is not ideal.

**Comment by jchavarri** [comment]
Hey @pirapira I think this is due to the way BuckleScript handles the generated files for the parser. In https://github.com/pirapira/bamboo/pull/262 these generated files were removed and thus more `make` statements were needed because the first attempt to compile fails (as the compiler can't find these files).

The reason why I checked them in https://github.com/pirapira/bamboo/pull/260 is because I realized this issue, and then saw a recommendation [in the official BuckleScript docs](https://bucklescript.github.io/bucklescript/Manual.html#_customize_rules_generators_support_since_1_7_4) to do so:

> It is quite common for programmers to use some preprocessors to generate some boilerplate code during developement.
> Note preprocessors can be classified in two categories: one is system-dependent which must be delayed until running on the target machines and the other is system-independent (such as lex, yacc, m4, re2c, etc.) which could be executed anytime.
> BuckleScript has built in support for conditional compilation for the second category. Since it is system-independent, we ask users to always generate such code and check it in before shipping, which would cut the dependencies for end users.

Tracking these files in git is not ideal either, but if it helps avoiding these issues in CI, then it might be worth it.

**Comment by pirapira** [comment]
I see.  I didn't know it's the recommendation of BuckleScript.

Anyway, I would like the build system to rebuild all dependent goals once I modify `parser.mly` or `lexer.mll`.
